# _config.yml
title: "My Personal Site"
description: "Personal website built with Jekyll on GitHub Pages."
# Pick a theme if you'd like (e.g. 'minima'):
# theme: minima

# Build settings
markdown: kramdown
plugins: []

# Optional: If you want to deploy at https://your-username.github.io
url: "https://your-username.github.io"
baseurl: ""  
