# _config.yml
title: "Mohamed Elsharkawy, MSc"
description: "Personal website showcasing research, publications, and CV."
markdown: kramdown
plugins: []
url: "https://sharkawy014700.github.io"
baseurl: ""
